# Generated by Django 4.2.7 on 2026-03-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_telegram_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegram_verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='user',
            name='sms_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
