# Generated by Django 4.2.7 on 2026-03-24 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. False means the record is deleted/inactive')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('water', 'Water'), ('fire', 'Fire'), ('electricity', 'Electricity'), ('road_damage', 'Road Damage')], db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryOrganization',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. False means the record is deleted/inactive')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category_organizations',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. False means the record is deleted/inactive')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sub_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. False means the record is deleted/inactive'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_bdc355_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_5cd1d4_idx'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='organizations.category'),
        ),
        migrations.AddField(
            model_name='categoryorganization',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_organizations', to='organizations.category'),
        ),
        migrations.AddField(
            model_name='categoryorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_organizations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='organizations',
            field=models.ManyToManyField(related_name='categories', through='organizations.CategoryOrganization', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['is_active'], name='sub_categor_is_acti_bdcb17_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'is_active'], name='sub_categor_categor_3a532a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='categoryorganization',
            index=models.Index(fields=['is_active'], name='category_or_is_acti_77c061_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryorganization',
            index=models.Index(fields=['category', 'organization'], name='category_or_categor_7714f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryorganization',
            unique_together={('category', 'organization')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='categories_is_acti_aae090_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='categories_name_98d7d5_idx'),
        ),
    ]
